modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="plotmod"
version="1.0.0"
displayName="PlotMod"
authors="DeinName"
description='''Ein Grundst√ºcksystem mit WorldEdit und Yawp, inkl. Kauf/Verkauf und persistenter Speicherung'''

[[dependencies.plotmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.plotmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.plotmod]]
modId="worldedit"
mandatory=true
versionRange="[7.2.15,)"
ordering="NONE"
side="BOTH"

[[dependencies.plotmod]]
modId="yawp"
mandatory=true
versionRange="[0.5.4,)"
ordering="NONE"
side="BOTH"
